/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSplatRouteImport } from './routes/api.$'
import { Route as AuthTenantsIndexRouteImport } from './routes/_auth/tenants/index'
import { Route as AuthPropertiesIndexRouteImport } from './routes/_auth/properties/index'
import { Route as AuthPaymentsIndexRouteImport } from './routes/_auth/payments/index'
import { Route as AuthLeasesIndexRouteImport } from './routes/_auth/leases/index'
import { Route as AuthDashboardIndexRouteImport } from './routes/_auth/dashboard/index'
import { Route as ApiRpcSplatRouteImport } from './routes/api.rpc.$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthPropertiesIdRouteImport } from './routes/_auth/properties/$id'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthTenantsIndexRoute = AuthTenantsIndexRouteImport.update({
  id: '/tenants/',
  path: '/tenants/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPropertiesIndexRoute = AuthPropertiesIndexRouteImport.update({
  id: '/properties/',
  path: '/properties/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPaymentsIndexRoute = AuthPaymentsIndexRouteImport.update({
  id: '/payments/',
  path: '/payments/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLeasesIndexRoute = AuthLeasesIndexRouteImport.update({
  id: '/leases/',
  path: '/leases/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDashboardIndexRoute = AuthDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => AuthRoute,
} as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthPropertiesIdRoute = AuthPropertiesIdRouteImport.update({
  id: '/properties/$id',
  path: '/properties/$id',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/api/$': typeof ApiSplatRoute
  '/properties/$id': typeof AuthPropertiesIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/dashboard/': typeof AuthDashboardIndexRoute
  '/leases/': typeof AuthLeasesIndexRoute
  '/payments/': typeof AuthPaymentsIndexRoute
  '/properties/': typeof AuthPropertiesIndexRoute
  '/tenants/': typeof AuthTenantsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/api/$': typeof ApiSplatRoute
  '/properties/$id': typeof AuthPropertiesIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/dashboard': typeof AuthDashboardIndexRoute
  '/leases': typeof AuthLeasesIndexRoute
  '/payments': typeof AuthPaymentsIndexRoute
  '/properties': typeof AuthPropertiesIndexRoute
  '/tenants': typeof AuthTenantsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/api/$': typeof ApiSplatRoute
  '/_auth/properties/$id': typeof AuthPropertiesIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/_auth/dashboard/': typeof AuthDashboardIndexRoute
  '/_auth/leases/': typeof AuthLeasesIndexRoute
  '/_auth/payments/': typeof AuthPaymentsIndexRoute
  '/_auth/properties/': typeof AuthPropertiesIndexRoute
  '/_auth/tenants/': typeof AuthTenantsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/login'
    | '/register'
    | '/api/$'
    | '/properties/$id'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/dashboard/'
    | '/leases/'
    | '/payments/'
    | '/properties/'
    | '/tenants/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/login'
    | '/register'
    | '/api/$'
    | '/properties/$id'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/dashboard'
    | '/leases'
    | '/payments'
    | '/properties'
    | '/tenants'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/about'
    | '/login'
    | '/register'
    | '/api/$'
    | '/_auth/properties/$id'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/_auth/dashboard/'
    | '/_auth/leases/'
    | '/_auth/payments/'
    | '/_auth/properties/'
    | '/_auth/tenants/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  AboutRoute: typeof AboutRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ApiSplatRoute: typeof ApiSplatRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/tenants/': {
      id: '/_auth/tenants/'
      path: '/tenants'
      fullPath: '/tenants/'
      preLoaderRoute: typeof AuthTenantsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/properties/': {
      id: '/_auth/properties/'
      path: '/properties'
      fullPath: '/properties/'
      preLoaderRoute: typeof AuthPropertiesIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/payments/': {
      id: '/_auth/payments/'
      path: '/payments'
      fullPath: '/payments/'
      preLoaderRoute: typeof AuthPaymentsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/leases/': {
      id: '/_auth/leases/'
      path: '/leases'
      fullPath: '/leases/'
      preLoaderRoute: typeof AuthLeasesIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboard/': {
      id: '/_auth/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthDashboardIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/properties/$id': {
      id: '/_auth/properties/$id'
      path: '/properties/$id'
      fullPath: '/properties/$id'
      preLoaderRoute: typeof AuthPropertiesIdRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthPropertiesIdRoute: typeof AuthPropertiesIdRoute
  AuthDashboardIndexRoute: typeof AuthDashboardIndexRoute
  AuthLeasesIndexRoute: typeof AuthLeasesIndexRoute
  AuthPaymentsIndexRoute: typeof AuthPaymentsIndexRoute
  AuthPropertiesIndexRoute: typeof AuthPropertiesIndexRoute
  AuthTenantsIndexRoute: typeof AuthTenantsIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthPropertiesIdRoute: AuthPropertiesIdRoute,
  AuthDashboardIndexRoute: AuthDashboardIndexRoute,
  AuthLeasesIndexRoute: AuthLeasesIndexRoute,
  AuthPaymentsIndexRoute: AuthPaymentsIndexRoute,
  AuthPropertiesIndexRoute: AuthPropertiesIndexRoute,
  AuthTenantsIndexRoute: AuthTenantsIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  AboutRoute: AboutRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ApiSplatRoute: ApiSplatRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
