include:
  - path: docker-compose.yaml

services:
  db:
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    secrets:
      - DB_PASSWORD
    entrypoint:
      [
        "bash",
        "-c",
        "export POSTGRES_PASSWORD=$(cat /run/secrets/db_password) && docker-entrypoint.sh postgres -c config_file=/etc/postgresql/postgresql.conf",
      ]
    ports:
      - "127.0.0.1:5432:5432"
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

secrets:
  db_password:
    file: ./secrets/db_password.txt
